version: '3.8'
services:
    database:
        image: 'postgres:11-alpine'
        restart: always
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        environment: 
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            PGDATA: /data/postgres
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        # image: omarlaz/backend:dev

